/**
 * Initial game catalog (M4): 26 content definitions covering every major
 * mechanic family — keyboard/key, letter, word, sentence, timed, survival,
 * adventure, advanced. CONTENT ONLY: no UI, no rewards, no unlock evaluation
 * (unlockRule is data for the progression system, later milestone).
 */
import type { GameDefinition } from "@tap/game-engine";

const OPEN = { type: "open" } as const;
const RETRY_OPEN = {
  maxAttemptsPerDay: null,
  cooldownSeconds: 0,
  expiresAfterSeconds: 900,
  allowRetry: true,
} as const;
const RETRY_TIMED = {
  maxAttemptsPerDay: 20,
  cooldownSeconds: 30,
  expiresAfterSeconds: 600,
  allowRetry: true,
} as const;

export const GAMES: GameDefinition[] = [
  {
    id: "game-find-the-key", slug: "find-the-key",
    title: { en: "Find the Key", bn: "কী খুঁজুন" },
    description: { en: "Press the single shown key.", bn: "দেখানো কী-টি চাপুন।" },
    worldSlug: "keyboard-village", category: "keyboard",
    mechanic: "target-press", mode: "letter", difficulty: "beginner",
    skillBands: ["beginner"],
    promptSource: { ref: "home-row", units: 10 },
    inputRules: { allowBackspace: false, caseSensitive: false },
    timingRules: { kind: "untimed" },
    scoringProfile: "standard", unlockRule: OPEN, attemptRules: RETRY_OPEN,
    theme: { visual: "village", audio: "calm" }, config: { targetsPerRound: 10 },
    competitionEligible: false, isActive: true, version: 1,
  },
  {
    id: "game-key-hunter", slug: "key-hunter",
    title: { en: "Key Hunter", bn: "কী শিকারি" },
    description: { en: "Locate highlighted keys fast.", bn: "হাইলাইট করা কী দ্রুত খুঁজুন।" },
    worldSlug: "keyboard-village", category: "keyboard",
    mechanic: "collection", mode: "letter", difficulty: "beginner",
    skillBands: ["beginner"],
    promptSource: { ref: "alphabet-lower", units: 12 },
    inputRules: { allowBackspace: false, caseSensitive: false },
    timingRules: { kind: "untimed" },
    scoringProfile: "standard", unlockRule: OPEN, attemptRules: RETRY_OPEN,
    theme: { visual: "village", audio: "calm" }, config: { targetsPerRound: 12 },
    competitionEligible: false, isActive: true, version: 1,
  },
  {
    id: "game-home-row-harbor", slug: "home-row-harbor",
    title: { en: "Home Row Harbor", bn: "হোম রো বন্দর" },
    description: { en: "Dock ships with home-row sequences.", bn: "হোম-রো ক্রমে জাহাজ ভিড়ান।" },
    worldSlug: "keyboard-village", category: "keyboard",
    mechanic: "sequence-build", mode: "letter", difficulty: "beginner",
    skillBands: ["beginner"],
    promptSource: { ref: "home-row", units: 14 },
    inputRules: { allowBackspace: true, caseSensitive: false },
    timingRules: { kind: "untimed" },
    scoringProfile: "standard", unlockRule: OPEN, attemptRules: RETRY_OPEN,
    theme: { visual: "harbor", audio: "calm" }, config: { sequenceLength: 14 },
    competitionEligible: false, isActive: true, version: 1,
  },
  {
    id: "game-finger-forge", slug: "finger-forge",
    title: { en: "Finger Forge", bn: "আঙুলের কর্মশালা" },
    description: { en: "Forge finger assignments in order.", bn: "ক্রমানুসারে আঙুলের কাজ শিখুন।" },
    worldSlug: "keyboard-village", category: "keyboard",
    mechanic: "sequence-build", mode: "letter", difficulty: "beginner",
    skillBands: ["beginner", "intermediate"],
    promptSource: { ref: "top-row", units: 14 },
    inputRules: { allowBackspace: true, caseSensitive: false },
    timingRules: { kind: "untimed" },
    scoringProfile: "standard",
    unlockRule: { op: "or", rules: [{ type: "gamesCompleted", gameSlugs: ["find-the-key"] }, { type: "level", min: 2 }] },
    attemptRules: RETRY_OPEN,
    theme: { visual: "forge", audio: "calm" }, config: { sequenceLength: 14 },
    competitionEligible: false, isActive: true, version: 1,
  },
  {
    id: "game-letter-rain", slug: "letter-rain",
    title: { en: "Letter Rain", bn: "অক্ষর বৃষ্টি" },
    description: { en: "Catch falling letters in time.", bn: "সময়মতো পড়ন্ত অক্ষর ধরুন।" },
    worldSlug: "letter-valley", category: "letter",
    mechanic: "falling-catch", mode: "letter", difficulty: "beginner",
    skillBands: ["beginner"],
    promptSource: { ref: "alphabet-lower", units: 20 },
    inputRules: { allowBackspace: false, caseSensitive: false },
    timingRules: { kind: "countdown", limitSeconds: 60 },
    scoringProfile: "standard", unlockRule: OPEN, attemptRules: RETRY_TIMED,
    theme: { visual: "rain", audio: "playful" }, config: { fallSpeed: 1 },
    competitionEligible: false, isActive: true, version: 1,
  },
  {
    id: "game-letter-hunt", slug: "letter-hunt",
    title: { en: "Letter Hunt", bn: "অক্ষর সন্ধান" },
    description: { en: "Find requested letters in the field.", bn: "মাঠ থেকে চাওয়া অক্ষর খুঁজুন।" },
    worldSlug: "letter-valley", category: "letter",
    mechanic: "collection", mode: "letter", difficulty: "beginner",
    skillBands: ["beginner"],
    promptSource: { ref: "alphabet-lower", units: 15 },
    inputRules: { allowBackspace: false, caseSensitive: false },
    timingRules: { kind: "untimed" },
    scoringProfile: "standard", unlockRule: OPEN, attemptRules: RETRY_OPEN,
    theme: { visual: "meadow", audio: "playful" }, config: { targetsPerRound: 15 },
    competitionEligible: false, isActive: true, version: 1,
  },
  {
    id: "game-letter-maze", slug: "letter-maze",
    title: { en: "Letter Maze", bn: "অক্ষর গোলকধাঁধা" },
    description: { en: "Navigate the maze letter by letter.", bn: "অক্ষরে অক্ষরে গোলকধাঁধা পার হোন।" },
    worldSlug: "letter-valley", category: "letter",
    mechanic: "escape-run", mode: "letter", difficulty: "intermediate",
    skillBands: ["beginner", "intermediate"],
    promptSource: { ref: "alphabet-lower", units: 24 },
    inputRules: { allowBackspace: true, caseSensitive: false },
    timingRules: { kind: "countup" },
    scoringProfile: "standard",
    unlockRule: { type: "level", min: 2 }, attemptRules: RETRY_OPEN,
    theme: { visual: "maze", audio: "tense" }, config: { mazeDepth: 3 },
    competitionEligible: false, isActive: true, version: 1,
  },
  {
    id: "game-word-builder", slug: "word-builder",
    title: { en: "Word Builder", bn: "শব্দ নির্মাতা" },
    description: { en: "Assemble simple words by typing.", bn: "টাইপ করে সহজ শব্দ গড়ুন।" },
    worldSlug: "word-city", category: "word",
    mechanic: "sequence-build", mode: "word", difficulty: "beginner",
    skillBands: ["beginner"],
    promptSource: { ref: "beginner-words", units: 8 },
    inputRules: { allowBackspace: true, caseSensitive: false },
    timingRules: { kind: "untimed" },
    scoringProfile: "standard", unlockRule: OPEN, attemptRules: RETRY_OPEN,
    theme: { visual: "city", audio: "playful" }, config: { wordsPerRound: 8 },
    competitionEligible: false, isActive: true, version: 1,
  },
  {
    id: "game-word-catcher", slug: "word-catcher",
    title: { en: "Word Catcher", bn: "শব্দ ধরা" },
    description: { en: "Catch falling words before they land.", bn: "পড়ন্ত শব্দ মাটিতে পড়ার আগেই ধরুন।" },
    worldSlug: "word-city", category: "word",
    mechanic: "falling-catch", mode: "word", difficulty: "beginner",
    skillBands: ["beginner"],
    promptSource: { ref: "beginner-words", units: 12 },
    inputRules: { allowBackspace: false, caseSensitive: false },
    timingRules: { kind: "countdown", limitSeconds: 60 },
    scoringProfile: "standard", unlockRule: OPEN, attemptRules: RETRY_TIMED,
    theme: { visual: "city", audio: "playful" }, config: { fallSpeed: 1 },
    competitionEligible: false, isActive: true, version: 1,
  },
  {
    id: "game-word-sprint", slug: "word-sprint",
    title: { en: "Word Sprint", bn: "শব্দ দৌড়" },
    description: { en: "Short timed word bursts.", bn: "অল্প সময়ে শব্দের ঝড়।" },
    worldSlug: "word-city", category: "word",
    mechanic: "time-trial", mode: "word", difficulty: "intermediate",
    skillBands: ["intermediate"],
    promptSource: { ref: "common-words", units: 30 },
    inputRules: { allowBackspace: true, caseSensitive: true },
    timingRules: { kind: "countdown", limitSeconds: 60 },
    scoringProfile: "speed",
    unlockRule: { type: "accuracy", min: 85 }, attemptRules: RETRY_TIMED,
    theme: { visual: "track", audio: "driving" }, config: { burstSeconds: 60 },
    competitionEligible: true, isActive: true, version: 1,
  },
  {
    id: "game-word-ninja", slug: "word-ninja",
    title: { en: "Word Ninja", bn: "শব্দ নিনজা" },
    description: { en: "Slice word targets with precision.", bn: "নির্ভুলভাবে শব্দ লক্ষ্য কাটুন।" },
    worldSlug: "word-city", category: "word",
    mechanic: "target-press", mode: "word", difficulty: "intermediate",
    skillBands: ["intermediate"],
    promptSource: { ref: "common-words", units: 20 },
    inputRules: { allowBackspace: false, caseSensitive: true },
    timingRules: { kind: "countdown", limitSeconds: 60 },
    scoringProfile: "standard",
    unlockRule: { type: "gamesCompleted", gameSlugs: ["word-builder", "word-catcher"] },
    attemptRules: RETRY_TIMED,
    theme: { visual: "dojo", audio: "tense" }, config: { targetsPerRound: 20 },
    competitionEligible: false, isActive: true, version: 1,
  },
  {
    id: "game-sentence-steps", slug: "sentence-steps",
    title: { en: "Sentence Steps", bn: "বাক্যের ধাপ" },
    description: { en: "Type short sentences step by step.", bn: "ধাপে ধাপে ছোট বাক্য লিখুন।" },
    worldSlug: "sentence-kingdom", category: "sentence",
    mechanic: "sequence-build", mode: "sentence", difficulty: "beginner",
    skillBands: ["beginner"],
    promptSource: { ref: "short-sentences", units: 4 },
    inputRules: { allowBackspace: true, caseSensitive: true },
    timingRules: { kind: "untimed" },
    scoringProfile: "standard", unlockRule: OPEN, attemptRules: RETRY_OPEN,
    theme: { visual: "kingdom", audio: "calm" }, config: { sentencesPerRound: 4 },
    competitionEligible: false, isActive: true, version: 1,
  },
  {
    id: "game-sentence-run", slug: "sentence-run",
    title: { en: "Sentence Run", bn: "বাক্য দৌড়" },
    description: { en: "Run checkpoints with sentence bursts.", bn: "বাক্যের ঝড়ে চেকপয়েন্ট পার হোন।" },
    worldSlug: "sentence-kingdom", category: "sentence",
    mechanic: "race-checkpoints", mode: "sentence", difficulty: "intermediate",
    skillBands: ["intermediate"],
    promptSource: { ref: "short-sentences", units: 6 },
    inputRules: { allowBackspace: true, caseSensitive: true },
    timingRules: { kind: "countup" },
    scoringProfile: "standard",
    unlockRule: { type: "level", min: 3 }, attemptRules: RETRY_OPEN,
    theme: { visual: "kingdom", audio: "driving" }, config: { checkpoints: 3 },
    competitionEligible: false, isActive: true, version: 1,
  },
  {
    id: "game-sentence-river", slug: "sentence-river",
    title: { en: "Sentence River", bn: "বাক্য নদী" },
    description: { en: "Cross the river before the current wins.", bn: "স্রোত জেতার আগেই নদী পার হোন।" },
    worldSlug: "sentence-kingdom", category: "sentence",
    mechanic: "escape-run", mode: "sentence", difficulty: "intermediate",
    skillBands: ["intermediate", "expert"],
    promptSource: { ref: "standard-sentences", units: 6 },
    inputRules: { allowBackspace: true, caseSensitive: true },
    timingRules: { kind: "countdown", limitSeconds: 120 },
    scoringProfile: "standard",
    unlockRule: { op: "and", rules: [{ type: "accuracy", min: 88 }, { type: "gamesCompleted", gameSlugs: ["sentence-steps"] }] },
    attemptRules: RETRY_TIMED,
    theme: { visual: "river", audio: "tense" }, config: { currentSpeed: 2 },
    competitionEligible: false, isActive: true, version: 1,
  },
  {
    id: "game-minute-dash", slug: "minute-dash",
    title: { en: "Minute Dash", bn: "এক মিনিটের দৌড়" },
    description: { en: "The classic one-minute typing test.", bn: "ক্লাসিক এক মিনিটের টাইপিং পরীক্ষা।" },
    worldSlug: "speed-arena", category: "timed",
    mechanic: "time-trial", mode: "mixed", difficulty: "intermediate",
    skillBands: ["intermediate"],
    promptSource: { ref: "standard-sentences", units: 12 },
    inputRules: { allowBackspace: true, caseSensitive: true },
    timingRules: { kind: "countdown", limitSeconds: 60 },
    scoringProfile: "speed",
    unlockRule: { type: "accuracy", min: 85 }, attemptRules: RETRY_TIMED,
    theme: { visual: "arena", audio: "driving" }, config: { durationSec: 60 },
    competitionEligible: true, isActive: true, version: 1,
  },
  {
    id: "game-two-minute-trail", slug: "two-minute-trail",
    title: { en: "Two-Minute Trail", bn: "দুই মিনিটের পথ" },
    description: { en: "A two-minute endurance benchmark.", bn: "দুই মিনিটের ধৈর্যের পরীক্ষা।" },
    worldSlug: "speed-arena", category: "timed",
    mechanic: "time-trial", mode: "mixed", difficulty: "intermediate",
    skillBands: ["intermediate", "expert"],
    promptSource: { ref: "standard-sentences", units: 24 },
    inputRules: { allowBackspace: true, caseSensitive: true },
    timingRules: { kind: "countdown", limitSeconds: 120 },
    scoringProfile: "speed",
    unlockRule: { type: "accuracy", min: 88 }, attemptRules: RETRY_TIMED,
    theme: { visual: "arena", audio: "driving" }, config: { durationSec: 120 },
    competitionEligible: true, isActive: true, version: 1,
  },
  {
    id: "game-speed-tunnel", slug: "speed-tunnel",
    title: { en: "Speed Tunnel", bn: "গতির সুড়ঙ্গ" },
    description: { en: "Hold top speed through the tunnel.", bn: "সুড়ঙ্গে সর্বোচ্চ গতি ধরে রাখুন।" },
    worldSlug: "speed-arena", category: "timed",
    mechanic: "race-checkpoints", mode: "mixed", difficulty: "expert",
    skillBands: ["expert"],
    promptSource: { ref: "standard-sentences", units: 18 },
    inputRules: { allowBackspace: true, caseSensitive: true },
    timingRules: { kind: "countdown", limitSeconds: 90 },
    scoringProfile: "speed",
    unlockRule: { op: "and", rules: [{ type: "wpm", min: 30 }, { type: "accuracy", min: 90 }] },
    attemptRules: RETRY_TIMED,
    theme: { visual: "tunnel", audio: "driving" }, config: { checkpoints: 4 },
    competitionEligible: true, isActive: true, version: 1,
  },
  {
    id: "game-accuracy-temple", slug: "accuracy-temple",
    title: { en: "Accuracy Temple", bn: "নির্ভুলতার মন্দির" },
    description: { en: "Worship precision under time pressure.", bn: "সময়ের চাপে নির্ভুলতার আরাধনা।" },
    worldSlug: "speed-arena", category: "timed",
    mechanic: "accuracy-trial", mode: "mixed", difficulty: "intermediate",
    skillBands: ["intermediate", "expert"],
    promptSource: { ref: "standard-sentences", units: 10 },
    inputRules: { allowBackspace: true, caseSensitive: true },
    timingRules: { kind: "countdown", limitSeconds: 60 },
    scoringProfile: "accuracy",
    unlockRule: { type: "accuracy", min: 85 }, attemptRules: RETRY_TIMED,
    theme: { visual: "temple", audio: "calm" }, config: { targetAccuracy: 95 },
    competitionEligible: true, isActive: true, version: 1,
  },
  {
    id: "game-combo-canyon", slug: "combo-canyon",
    title: { en: "Combo Canyon", bn: "কম্বো গিরিখাত" },
    description: { en: "Chain correct streaks across waves.", bn: "ঢেউ পেরিয়ে সঠিক ধারা বজায় রাখুন।" },
    worldSlug: "volcano-zone", category: "survival",
    mechanic: "survival-waves", mode: "mixed", difficulty: "intermediate",
    skillBands: ["intermediate"],
    promptSource: { ref: "common-words", units: 40 },
    inputRules: { allowBackspace: false, caseSensitive: true },
    timingRules: { kind: "countup" },
    scoringProfile: "survival",
    unlockRule: { type: "level", min: 4 }, attemptRules: RETRY_OPEN,
    theme: { visual: "canyon", audio: "tense" }, config: { waves: 5 },
    competitionEligible: false, isActive: true, version: 1,
  },
  {
    id: "game-no-mistake-bridge", slug: "no-mistake-bridge",
    title: { en: "No-Mistake Bridge", bn: "নির্ভুল সেতু" },
    description: { en: "Cross with a perfect run.", bn: "নিখুঁত পারফরম্যান্সে সেতু পার হোন।" },
    worldSlug: "castle-siege", category: "survival",
    mechanic: "survival-waves", mode: "word", difficulty: "expert",
    skillBands: ["expert"],
    promptSource: { ref: "common-words", units: 30 },
    inputRules: { allowBackspace: false, caseSensitive: true },
    timingRules: { kind: "countup" },
    scoringProfile: "accuracy",
    unlockRule: { op: "and", rules: [{ type: "accuracy", min: 92 }, { type: "level", min: 5 }] },
    attemptRules: RETRY_OPEN,
    theme: { visual: "bridge", audio: "tense" }, config: { waves: 3, flawlessOnly: true },
    competitionEligible: false, isActive: true, version: 1,
  },
  {
    id: "game-jungle-escape", slug: "jungle-escape",
    title: { en: "Jungle Escape", bn: "জঙ্গল থেকে পলায়ন" },
    description: { en: "Escape timed jungle checkpoints.", bn: "সময়মতো জঙ্গলের চেকপয়েন্ট পালান।" },
    worldSlug: "jungle-escape", category: "adventure",
    mechanic: "escape-run", mode: "sentence", difficulty: "intermediate",
    skillBands: ["intermediate"],
    promptSource: { ref: "short-sentences", units: 8 },
    inputRules: { allowBackspace: true, caseSensitive: true },
    timingRules: { kind: "countdown", limitSeconds: 120 },
    scoringProfile: "standard",
    unlockRule: { type: "level", min: 3 }, attemptRules: RETRY_TIMED,
    theme: { visual: "jungle", audio: "tense" }, config: { checkpoints: 4 },
    competitionEligible: false, isActive: true, version: 1,
  },
  {
    id: "game-sky-typist", slug: "sky-typist",
    title: { en: "Sky Typist", bn: "আকাশ টাইপিস্ট" },
    description: { en: "Fly through word gates in the sky.", bn: "আকাশে শব্দ গেট পেরিয়ে উড়ুন।" },
    worldSlug: "sky-frontier", category: "adventure",
    mechanic: "race-checkpoints", mode: "word", difficulty: "intermediate",
    skillBands: ["beginner", "intermediate"],
    promptSource: { ref: "common-words", units: 25 },
    inputRules: { allowBackspace: true, caseSensitive: true },
    timingRules: { kind: "countup" },
    scoringProfile: "standard",
    unlockRule: { type: "level", min: 2 }, attemptRules: RETRY_OPEN,
    theme: { visual: "sky", audio: "driving" }, config: { checkpoints: 5 },
    competitionEligible: false, isActive: true, version: 1,
  },
  {
    id: "game-space-run", slug: "space-run",
    title: { en: "Space Run", bn: "মহাকাশ দৌড়" },
    description: { en: "Navigate a space course by typing.", bn: "টাইপ করে মহাকাশ পথ পাড়ি দিন।" },
    worldSlug: "space-station", category: "adventure",
    mechanic: "escape-run", mode: "mixed", difficulty: "expert",
    skillBands: ["expert"],
    promptSource: { ref: "standard-sentences", units: 10 },
    inputRules: { allowBackspace: true, caseSensitive: true },
    timingRules: { kind: "countdown", limitSeconds: 180 },
    scoringProfile: "standard",
    unlockRule: { op: "and", rules: [{ type: "level", min: 6 }, { type: "accuracy", min: 90 }] },
    attemptRules: RETRY_TIMED,
    theme: { visual: "space", audio: "epic" }, config: { checkpoints: 5 },
    competitionEligible: false, isActive: true, version: 1,
  },
  {
    id: "game-word-sniper", slug: "word-sniper",
    title: { en: "Word Sniper", bn: "শব্দ স্নাইপার" },
    description: { en: "Hit exact words among decoys.", bn: "ভিড়ের মধ্যে সঠিক শব্দে আঘাত করুন।" },
    worldSlug: "cyber-city", category: "advanced",
    mechanic: "target-press", mode: "word", difficulty: "expert",
    skillBands: ["expert"],
    promptSource: { ref: "common-words", units: 20 },
    inputRules: { allowBackspace: false, caseSensitive: true },
    timingRules: { kind: "countdown", limitSeconds: 60 },
    scoringProfile: "accuracy",
    unlockRule: { op: "and", rules: [{ type: "accuracy", min: 90 }, { type: "gamesCompleted", gameSlugs: ["word-ninja"] }] },
    attemptRules: RETRY_TIMED,
    theme: { visual: "neon", audio: "tense" }, config: { decoysPerRound: 4 },
    competitionEligible: true, isActive: true, version: 1,
  },
  {
    id: "game-sentence-blitz", slug: "sentence-blitz",
    title: { en: "Sentence Blitz", bn: "বাক্য ব্লিটজ" },
    description: { en: "Rapid sentence bursts at expert pace.", bn: "এক্সপার্ট গতিতে দ্রুত বাক্যের ঝড়।" },
    worldSlug: "grand-arena", category: "advanced",
    mechanic: "time-trial", mode: "sentence", difficulty: "expert",
    skillBands: ["expert"],
    promptSource: { ref: "standard-sentences", units: 12 },
    inputRules: { allowBackspace: true, caseSensitive: true },
    timingRules: { kind: "countdown", limitSeconds: 60 },
    scoringProfile: "speed",
    unlockRule: { op: "and", rules: [{ type: "wpm", min: 35 }, { type: "accuracy", min: 90 }] },
    attemptRules: RETRY_TIMED,
    theme: { visual: "arena", audio: "epic" }, config: { durationSec: 60 },
    competitionEligible: true, isActive: true, version: 1,
  },
  {
    id: "game-precision-grid", slug: "precision-grid",
    title: { en: "Precision Grid", bn: "নির্ভুল গ্রিড" },
    description: { en: "Master symbols on a shrinking grid.", bn: "সংকুচিত গ্রিডে চিহ্ন আয়ত্ত করুন।" },
    worldSlug: "cyber-city", category: "advanced",
    mechanic: "accuracy-trial", mode: "symbol", difficulty: "expert",
    skillBands: ["expert"],
    promptSource: { ref: "symbols", units: 24 },
    inputRules: { allowBackspace: false, caseSensitive: true },
    timingRules: { kind: "countdown", limitSeconds: 60 },
    scoringProfile: "accuracy",
    unlockRule: { type: "accuracy", min: 88 }, attemptRules: RETRY_TIMED,
    theme: { visual: "grid", audio: "tense" }, config: { gridSize: 6 },
    competitionEligible: false, isActive: true, version: 1,
  },
];
